### ISSUE TITLE
chrome process hangs forever

### ISSUE THREAD

**Issue by beeflamian** [karma-runner/karma-chrome-launcher#76]
Karma seems have problem disconnecting chrome browser. It happened to me about every 10 tests run. I cannot constantly reproduce this problem

OS: CentOS7
Chrome: Google Chrome 52.0.2743.116
Karma chrome launcher: tried 1.0.1, 0.2.3, 0.1.4, and they all have the problem

Some log:
Finished in 3.517 secs / 2.243 secs

SUMMARY:
✔︎ 9 tests completed
DEBUG [karma]: Run complete, exitting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [launcher]: Disconnecting all browsers
DEBUG [launcher]: Disconnecting all browsers
...then wait forever

The process tree can be found here https://gist.github.com/beeflamian/336735330443814d442fe77fc8e5f9f4

karma config file can be found here
https://gist.github.com/beeflamian/180dc8565e39509c11ee61f6cf844f38

Does anyone have any suggestions? Thanks in advance!

**Comment by dignifiedquire** [comment]
This sounds like the actual Chrome process gets somehow stuck, so that karma can't kill it with a regular signal. Have you checked if Chrome some hangs or reacts to a regular close command?

**Comment by beeflamian** [comment]
@dignifiedquire Here's a high level note https://gist.github.com/beeflamian/07ebb8254e1f92d83296a85610b3fbfe

I've also tried to narrow it down by printing stacktrace of chrome. However, I only found chrome is pretty complex that has fingers everywhere. I suspect there is a dead lock among threads :(

**Comment by dignifiedquire** [comment]
Yeah that looks like Chrome hangs itself for some reason. It's probably related to what is actually run inside your tests.

**Comment by myitcv** [comment]
I'm seeing the same thing. 

```
Ubuntu 16.04.1 LTS
Google Chrome 53.0.2785.70 beta
```

The problem appears to be related to Chrome launching a subprocess (`gcr-prompter`) that prompts for a password to unlock my keychain (I believe this is something to do with gnome keyring support - I have no need for this)

Chrome spawns `gcr-prompter`. So even when the tests finish, `gcr-prompter` is still waiting for user input (their password), hence Chrome is waiting on `gcr-prompter`, hence why it doesn't die when expected, hence the resulting resort to sending SIGKILL.

My brute force solution to this was to remove the following packages:

```
libfolks-eds25 gnome-keyring seahorse gcr evolution-data-server oneconf python-ubuntuone-storageprotocol ubuntu-sso-client python-ubuntu-sso-client pinentry-gnome3
```

But it would seem cleaner to be able to launch Chrome in such a way that it does not try to kick start the gnome keyring process. I've no idea how to do that...

**Comment by voltrevo** [comment]
@beeflamian @myitcv Can you repro in the latest Karma? It's possible you ran into this issue which was fixed: https://github.com/karma-runner/karma/pull/2267.

**Comment by myitcv** [comment]
@voltrevo any reason why you think the two are related?

**Comment by ValeryVS** [comment]
```
karma 1.3.0
karma-chrome-launcher 2.0.0
Ubuntu 14.04.5 LTS
Google Chrome Version 53.0.2785.116 (64-bit)
```
It prompts for a password to unlock keychain.

But with Chromium (not Chrome) all ok. Also with karma 1.20.

```
karma 1.2.0
karma-chrome-launcher 2.0.0
Ubuntu 14.04.5 LTS
Chromium Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)
```

**Comment by michaelBenin** [comment]
Also running into this problem, first of all the docs on karma's 1.0 says it doesn't need anything to open chrome, which is wrong, you still need this plugin, tested on mac. Unfortunately on Ubuntu with the plugin and the CHROME_BIN set, it's having an issue. This was working with the older version of Karma. 

Here's the stack trace I'm getting: 

```
21 10 2016 16:41:14.622:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
21 10 2016 16:41:14.624:INFO [launcher]: Launching browser Chrome with unlimited concurrency
21 10 2016 16:41:14.643:INFO [launcher]: Starting browser Chrome
21 10 2016 16:42:14.705:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
21 10 2016 16:42:16.710:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.
21 10 2016 16:42:18.713:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing.
[16:42:18] 'client-unit-test' errored after 1.08 min
```

**Comment by michaelBenin** [comment]
Also, should we open an issue on karma? In it's docs it says chrome comes with it.

**Comment by bennyn** [comment]
I got the same issue on Windows 10 with:
- karma v1.7.1
- karma-chrome-launcher v2.2.0

Screenshot:

![unbenannt](https://user-images.githubusercontent.com/469989/33994118-95c4034a-e0d9-11e7-9f23-e5f157952031.PNG)

Relevant Karma Browser config:

```javascript
browsers: ['ChromeNoSandbox'],
customLaunchers: {
  ChromeNoSandbox: {
    base: 'ChromeHeadless',
    flags: ['--no-sandbox'],
  },
}
```

When my test suite is empty, then Chrome can be closed by Karma:

> HeadlessChrome 0.0.0 (Windows 10 0.0.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
HeadlessChrome 0.0.0 (Windows 10 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
HeadlessChrome 0.0.0 (Windows 10 0.0.0): Executed 0 of 8 DISCONNECTED (10.02 secs / 0 secs)
14 12 2017 14:16:46.860:WARN [karma]: Test suite was empty.

**Comment by thirusabari** [comment]
Hi @bennyn ,

flags: ['--no-sandbox'] was not worked for me.

Still I am getting same Error in Chromeheadless 

Thanks

**Comment by ribrdb** [comment]
I fixed this on darwin by using the chrome flag --use-mock-keychain
For linux --password-store=basic sounds like it might work.

**Comment by govindrai** [comment]
Any concrete solution to this? This is still happening for me.

**Comment by chirilaalexandru90** [comment]
> Any concrete solution to this? This is still happening for me.

Same problem

**Comment by lfdantoni** [comment]
> Any concrete solution to this? This is still happening for me.

same problem to me

**Comment by joeldlc** [comment]
> > Any concrete solution to this? This is still happening for me.
> 
> same problem to me

Same problem.

**Comment by tobiasetter** [comment]
> 
> 
> > > Any concrete solution to this? This is still happening for me.
> > 
> > 
> > same problem to me
> 
> Same problem.

same for me

**Comment by alex-jesper** [comment]
Setting 
> singleRun: true
Did the trick for for me

**Comment by tmagandr** [comment]
same problem for me too. Any solution appreciated?
